
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 05 09:35:20 EST 2014
//----------------------------------------------------

package ast;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQVQ = 22;
  public static final int LBRACKET = 34;
  public static final int CHAR = 60;
  public static final int CONCAT = 56;
  public static final int GEQUAL = 42;
  public static final int READINT = 13;
  public static final int EQUALQ = 23;
  public static final int CASE = 9;
  public static final int CAR = 17;
  public static final int DOUBLE = 58;
  public static final int CDR = 18;
  public static final int LPAREN = 25;
  public static final int SEMI = 30;
  public static final int INT = 57;
  public static final int HEX = 63;
  public static final int PRINTLN = 11;
  public static final int MINUS = 51;
  public static final int RPAREN = 26;
  public static final int LTHAN = 38;
  public static final int COMMA = 27;
  public static final int LAZY = 14;
  public static final int CALL = 4;
  public static final int DIV = 53;
  public static final int BNOT = 49;
  public static final int BAND = 47;
  public static final int VECRIGHT = 33;
  public static final int PLUS = 50;
  public static final int ASSIGN = 55;
  public static final int IF = 6;
  public static final int EOF = 0;
  public static final int LNOT = 46;
  public static final int LAND = 44;
  public static final int EQUAL = 40;
  public static final int RBRACKET = 35;
  public static final int TRUE = 36;
  public static final int SIZE = 20;
  public static final int error = 1;
  public static final int MUL = 52;
  public static final int LOR = 45;
  public static final int MOD = 54;
  public static final int PAIR = 15;
  public static final int GTHAN = 39;
  public static final int COLON = 31;
  public static final int BIN = 62;
  public static final int BOR = 48;
  public static final int LBRACE = 28;
  public static final int ELSE = 8;
  public static final int PAIRQ = 16;
  public static final int WS = 64;
  public static final int VARIABLE = 59;
  public static final int BE = 24;
  public static final int LEQUAL = 41;
  public static final int READ = 12;
  public static final int NEQUAL = 43;
  public static final int LIST = 19;
  public static final int SUBSTR = 21;
  public static final int LET = 5;
  public static final int THEN = 7;
  public static final int RBRACE = 29;
  public static final int STRING = 61;
  public static final int PROC = 2;
  public static final int DEF = 3;
  public static final int FALSE = 37;
  public static final int VECLEFT = 32;
  public static final int PRINT = 10;
}

