
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 23 19:54:22 GMT-05:00 2009
//----------------------------------------------------

package smpl.lang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BNOT = 66;
  public static final int GT = 69;
  public static final int READ = 41;
  public static final int LCOMMENT = 12;
  public static final int NEWLINE = 48;
  public static final int EXPORT = 18;
  public static final int GE = 70;
  public static final int VRBRACKET = 3;
  public static final int SEMI = 73;
  public static final int CONSTRUCTOR = 16;
  public static final int SPACE = 46;
  public static final int CATCH = 80;
  public static final int COMMA = 75;
  public static final int RBRACE = 9;
  public static final int RPAREN = 7;
  public static final int HEXINT = 84;
  public static final int LT = 67;
  public static final int INTEGER = 83;
  public static final int DOUBLE = 86;
  public static final int LBRACE = 8;
  public static final int BININT = 85;
  public static final int LPAREN = 6;
  public static final int FALSE = 52;
  public static final int NOT = 63;
  public static final int DEF = 33;
  public static final int LE = 68;
  public static final int NIL = 53;
  public static final int VAR = 90;
  public static final int READINT = 42;
  public static final int THEN = 36;
  public static final int VLBRACKET = 2;
  public static final int PROC = 30;
  public static final int CLOSEQUOTE = 11;
  public static final int EQ = 71;
  public static final int PRINTLN = 40;
  public static final int CLASS = 15;
  public static final int MULTIPLY = 57;
  public static final int CDR = 22;
  public static final int MODULO = 59;
  public static final int TRUE = 51;
  public static final int TAB = 47;
  public static final int PLUS = 54;
  public static final int ISPAIR = 27;
  public static final int DIVIDE = 58;
  public static final int WHILE = 44;
  public static final int CHAR = 87;
  public static final int ASSIGN = 76;
  public static final int FOR = 43;
  public static final int THREAD = 82;
  public static final int CONCAT = 77;
  public static final int TRY = 79;
  public static final int ELSE = 37;
  public static final int BREAK = 45;
  public static final int DOT = 78;
  public static final int POWER = 60;
  public static final int EOF = 0;
  public static final int ISEQV = 28;
  public static final int OPENQUOTE = 10;
  public static final int BAND = 64;
  public static final int PRINT = 39;
  public static final int BOR = 65;
  public static final int ISEQ = 29;
  public static final int CRETURN = 49;
  public static final int MINUS = 55;
  public static final int METHOD = 19;
  public static final int OR = 62;
  public static final int error = 1;
  public static final int START = 81;
  public static final int PAIR = 20;
  public static final int LIST = 23;
  public static final int IF = 35;
  public static final int ID = 89;
  public static final int COLON = 74;
  public static final int RBRACKET = 5;
  public static final int RCOMMENT = 13;
  public static final int LAZY = 34;
  public static final int CASE = 38;
  public static final int NEW = 14;
  public static final int STRING = 88;
  public static final int SIZE = 24;
  public static final int CAR = 21;
  public static final int SHARED = 17;
  public static final int BE = 32;
  public static final int AND = 61;
  public static final int UMINUS = 56;
  public static final int SUBSTR = 25;
  public static final int LBRACKET = 4;
  public static final int LET = 31;
  public static final int NE = 72;
  public static final int CALL = 26;
  public static final int FORMFEED = 50;
}

