
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Fri Dec 28 19:31:07 GMT-05:00 2012
//----------------------------------------------------

package lang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQVQ = 54;
  public static final int LBRACKET = 10;
  public static final int CHAR = 61;
  public static final int CONCAT = 34;
  public static final int EQUALQ = 55;
  public static final int READINT = 46;
  public static final int GEQUAL = 26;
  public static final int CAR = 49;
  public static final int CASE = 42;
  public static final int DOUBLE = 57;
  public static final int CDR = 50;
  public static final int LPAREN = 2;
  public static final int SEMI = 4;
  public static final int INT = 60;
  public static final int HEX = 58;
  public static final int PRINTLN = 44;
  public static final int MINUS = 17;
  public static final int RPAREN = 3;
  public static final int LTHAN = 29;
  public static final int NIL = 13;
  public static final int LAZY = 47;
  public static final int COMMA = 5;
  public static final int CALL = 37;
  public static final int BAND = 22;
  public static final int DIV = 19;
  public static final int BNOT = 24;
  public static final int VECRIGHT = 9;
  public static final int PLUS = 16;
  public static final int IF = 39;
  public static final int ASSIGN = 21;
  public static final int EOF = 0;
  public static final int LNOT = 33;
  public static final int LAND = 31;
  public static final int RBRACKET = 11;
  public static final int EQUAL = 30;
  public static final int SIZE = 53;
  public static final int TRUE = 14;
  public static final int error = 1;
  public static final int MUL = 18;
  public static final int LOR = 32;
  public static final int MOD = 20;
  public static final int PAIR = 48;
  public static final int GTHAN = 28;
  public static final int COLON = 12;
  public static final int BIN = 59;
  public static final int ELSE = 41;
  public static final int BOR = 23;
  public static final int LBRACE = 6;
  public static final int PAIRQ = 51;
  public static final int WS = 65;
  public static final int BE = 64;
  public static final int VARIABLE = 63;
  public static final int READ = 45;
  public static final int LEQUAL = 27;
  public static final int LIST = 52;
  public static final int NEQUAL = 25;
  public static final int SUBSTR = 56;
  public static final int LET = 38;
  public static final int THEN = 40;
  public static final int RBRACE = 7;
  public static final int STRING = 62;
  public static final int PROC = 35;
  public static final int DEF = 36;
  public static final int FALSE = 15;
  public static final int VECLEFT = 8;
  public static final int PRINT = 43;
}

